apiVersion: v1
kind: Pod
metadata:
  name: healthcheck
  labels:
    pod: nginx
spec:
  containers:
    - name: nginx
      image: zembutsu/docker-sample-nginx:1.0
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 3
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 1
      readinessProbe:
        exec:
          command: ["ls", "/usr/share/nginx/html/50x.html"]
        initialDelaySeconds: 3
        periodSeconds: 10
