apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - image: zembutsu/docker-sample-nginx:1.0
      name: nginx-hostpath
      volumeMounts:
        - mountPath: /srv
          name: hostpath
  volumes:
    - name: hostpath
      hostPath:
        path: /data
        type: DirectoryOrCreate
