apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: nfs
    environment: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    server: xxx.xxx.xxx.xxx
    path: /nfs/sample
