apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
    - name: init-container
      image: centos:latest
      command: ['sh', '-c', 'echo init_test']
  containers:
    - name: nginx
      image: zembutsu/docker-sample-nginx:1.0
      ports:
        - containerPort: 80
