apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-pod
spec:
  containers:
    - name: nginx
      image: zembutsu/docker-sample-nginx:1.0
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-c", "ls /usr/share/nginx/html/ > /tmp/list; sleep 3600"]
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "touch /usr/share/nginx/html/postStart.txt"]
        preStop:
          exec:
            command: ["/bin/sh", "-c", "touch /usr/share/nginx/html/preStop.txt; sleep 30"]
