apiVersion: v1
kind: Pod
metadata:
  name: sample-privileged-pod
spec:
  containers:
    - name: nginx
      image: zembutsu/docker-sample-nginx:1.0
      ports:
        - containerPort: 80
      securityContext:
        privileged: true
