apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 0.2
    defaultRequest:
      memory: 128Mi
      cpu: 0.1
    max:
      memory: 1Gi
      cpu: 1000m
    min:
      memory: 64Mi
      cpu: 50m
    type: Container
