apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quotas
  namespace: project1
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "10"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
    services.nodeports: "2"
    resourcequotas: 1
