apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: nginx
  template:
    metadata:
      labels:
        pod: nginx
    spec:
      containers:
        - name: nginx
          image: zembutsu/docker-sample-nginx:1.0
          ports:
            - containerPort: 80
