apiVersion: v1
kind: Pod
metadata:
  name: volume-configmap
spec:
  containers:
    - name: nginx-configmap
      image: zembutsu/docker-sample-nginx:1.0
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: nginx
        items:
          - key: nginx.conf
            path: nginx.conf
